### ISSUE TITLE
Doesn't work with the whole Path

### ISSUE THREAD

**Issue by TorbenWetter** [AlpixTM/transfersh#1]
Hey,
very useful package!
But if I try to upload a file given its Path (if I'm not in the file's folder) it fails. :(

torben@torben-wetter:~/Desktop$ transfersh /home/torben/Desktop/photo5246905325410428941.jpg
 ====== Transfersh ===== 
Unofficial command-line client for https://transfer.sh/ based on python 
by Alpix (https://alpix.eu) 
contribute: https://github.com/AlpixTM/transfersh
/home/torben/Desktop/photo5246905325410428941.jpg
Not Found

**Comment by AlpixTM** [comment]
yeah, know that bug.
Thank you for reporting it :)
Will be fixed soon!

**Comment by AlpixTM** [comment]
Fixed
