### ISSUE TITLE
New feature to be added

### ISSUE THREAD

**Issue by ghost** [AlpixTM/transfersh#2]
Please add a "loading bar" to be enabled by default so you know how much time is left till the upload is complete

**Comment by AlpixTM** [comment]
I will consider it.

May i know on which OS you run it?

Kindest regards,
Alpix

**Comment by AlpixTM** [comment]
Hello,
its now added with arg -p https://github.com/AlpixTM/transfersh/commit/810454a68e395fac736867d0a3e8cf494dbbbae4
