### ISSUE TITLE
Malformed progress bar output in terminal emulator

### ISSUE THREAD

**Issue by aj-m** [AlpixTM/transfersh#4]
The progress bar doesn't currently account for terminal width. Additionally, the carriage returns aren't properly clearing the line in gnome-terminal - this is especially noticeable on larger files.

![image](https://user-images.githubusercontent.com/2524348/51866644-1c6e8f00-230f-11e9-83b7-65beb3426900.png)
[lorem.txt](https://github.com/AlpixTM/transfersh/files/2804962/lorem.txt)

![image](https://user-images.githubusercontent.com/2524348/51866684-37410380-230f-11e9-8145-12e7180d9cf2.png)
[sound file](https://transfer.sh/QCRJt/Ice%20barrage%20sound.m4a)

**Comment by AlpixTM** [comment]
Jep,

the default bar width of 1 character per percent needs to be  dynamically adjust to the available chars per line in the terminal.
Having progress bars as long as one line in the terminal should also eliminate the cleaning problem.

Thank you for pointing this out.

I will take a look in this tomorrow.
Im not realy happy with this implementation of this progress bar, it is more like a first version.
